### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by pmxpo** [mhmmdbdrhmd/Football-Match-Predictor#1]
Interesting

**Comment by mhmmdbdrhmd** [comment]
> if you have a licence or ownership, i will gladly remove this project. Was not even that great to be on my profile, it was most accessible to be uploaded here as i coded it recently. So, no big deal :)

**Comment by mhmmdbdrhmd** [comment]
seems you are right, I should have not uploaded this project here as I have done it for a client in freelancer.com and the client has ownership of the code (although i have changed it a bit)
Anyhow, since i have updated this code a bit, I wait for you to download it (or not) and once you replied this ticked, I will remove this repository. 

This was an honest mistake, I thought client and programmer share the ownership. happy to remove it after your request.

**Comment by mhmmdbdrhmd** [comment]
or i can transfer the ownership to u

**Comment by pmxpo** [comment]
I am the freelancer you developed the code for. I understand that there're improvements required but,I am surprised to see you post it here. 

Anyway I respect your sportsmanship and honesty.

In the current circumstance, I actually own the code.

**Comment by mhmmdbdrhmd** [comment]
I am open to
remove the project or just transfer the ownership to you,
since I already wrote the readme file. No point in wasting the readme file.

Cheers,
Mo.

**Comment by mhmmdbdrhmd** [comment]
If it is ok, may I ask you to send me a message in freelancer.com so i can verify this is your github account. And I will transfer the ownership (just checked it, its possible)

**Comment by mhmmdbdrhmd** [comment]
Repository Transfer requested.
